language: php

os:
  - linux

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer install -n --dev --prefer-source
  - gem install mailcatcher
  - mkdir -p /home/travis/.phpenv/versions/$(phpenv version-name)/etc/conf.d
  - phpenv config-add tests/Resources/travis.php.ini
  - mailcatcher
